"""initial schema

Revision ID: 13516194a2b1
Revises: 
Create Date: 2026-06-27 13:38:11.881059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13516194a2b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE contract_specifications_id_seq')
    op.create_table('contract_specifications',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('planned_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'product_id', name='uq_contract_product')
    )
    op.create_index(op.f('ix_contract_specifications_contract_id'), 'contract_specifications', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_specifications_created_by'), 'contract_specifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_contract_specifications_deleted_at'), 'contract_specifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contract_specifications_product_id'), 'contract_specifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_contract_specifications_updated_by'), 'contract_specifications', ['updated_by'], unique=False)
    op.create_index(op.f('ix_contract_specifications_uuid'), 'contract_specifications', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE contracts_id_seq')
    op.create_table('contracts',
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('contragent_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'UZS', name='currency', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='contractstatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_contragent_id'), 'contracts', ['contragent_id'], unique=False)
    op.create_index(op.f('ix_contracts_created_by'), 'contracts', ['created_by'], unique=False)
    op.create_index(op.f('ix_contracts_deleted_at'), 'contracts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_updated_by'), 'contracts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_contracts_uuid'), 'contracts', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE contragents_id_seq')
    op.create_table('contragents',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_index(op.f('ix_contragents_created_by'), 'contragents', ['created_by'], unique=False)
    op.create_index(op.f('ix_contragents_deleted_at'), 'contragents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contragents_name'), 'contragents', ['name'], unique=False)
    op.create_index(op.f('ix_contragents_updated_by'), 'contragents', ['updated_by'], unique=False)
    op.create_index(op.f('ix_contragents_uuid'), 'contragents', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE exchange_rates_id_seq')
    op.create_table('exchange_rates',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('usd_to_uzs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_created_by'), 'exchange_rates', ['created_by'], unique=False)
    op.create_index(op.f('ix_exchange_rates_deleted_at'), 'exchange_rates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_date'), 'exchange_rates', ['rate_date'], unique=True)
    op.create_index(op.f('ix_exchange_rates_updated_by'), 'exchange_rates', ['updated_by'], unique=False)
    op.create_index(op.f('ix_exchange_rates_uuid'), 'exchange_rates', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE payment_allocations_id_seq')
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_created_by'), 'payment_allocations', ['created_by'], unique=False)
    op.create_index(op.f('ix_payment_allocations_deleted_at'), 'payment_allocations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_shipment_id'), 'payment_allocations', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_updated_by'), 'payment_allocations', ['updated_by'], unique=False)
    op.create_index(op.f('ix_payment_allocations_uuid'), 'payment_allocations', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE payments_id_seq')
    op.create_table('payments',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'UZS', name='currency', native_enum=False, length=10), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'REGULAR', 'OVERPAYMENT', name='paymenttype', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_contract_id'), 'payments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payments_created_by'), 'payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_payments_deleted_at'), 'payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_updated_by'), 'payments', ['updated_by'], unique=False)
    op.create_index(op.f('ix_payments_uuid'), 'payments', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE products_id_seq')
    op.create_table('products',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_updated_by'), 'products', ['updated_by'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE shipment_items_id_seq')
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_created_by'), 'shipment_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_shipment_items_deleted_at'), 'shipment_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shipment_items_product_id'), 'shipment_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_updated_by'), 'shipment_items', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shipment_items_uuid'), 'shipment_items', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE shipments_id_seq')
    op.create_table('shipments',
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('ttn_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_contract_id'), 'shipments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_shipments_created_by'), 'shipments', ['created_by'], unique=False)
    op.create_index(op.f('ix_shipments_deleted_at'), 'shipments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shipments_invoice_number'), 'shipments', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_date'), 'shipments', ['shipment_date'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_shipments_ttn_number'), 'shipments', ['ttn_number'], unique=False)
    op.create_index(op.f('ix_shipments_updated_by'), 'shipments', ['updated_by'], unique=False)
    op.create_index(op.f('ix_shipments_uuid'), 'shipments', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE sync_logs_id_seq')
    op.create_table('sync_logs',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('EXPORT', 'IMPORT', name='syncdirection', native_enum=False, length=10), nullable=False),
    sa.Column('package_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'CONFLICT', name='syncstatus', native_enum=False, length=10), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conflicts_count', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_created_by'), 'sync_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_sync_logs_deleted_at'), 'sync_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_device_id'), 'sync_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_updated_by'), 'sync_logs', ['updated_by'], unique=False)
    op.create_index(op.f('ix_sync_logs_uuid'), 'sync_logs', ['uuid'], unique=True)
    op.execute('CREATE SEQUENCE users_id_seq')
    op.create_table('users',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_table('users')
    op.execute('DROP SEQUENCE IF EXISTS users_id_seq')
    op.drop_index(op.f('ix_sync_logs_uuid'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_updated_by'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_device_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_deleted_at'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_created_by'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.execute('DROP SEQUENCE IF EXISTS sync_logs_id_seq')
    op.drop_index(op.f('ix_shipments_uuid'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_updated_by'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_ttn_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_invoice_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_deleted_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_by'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_contract_id'), table_name='shipments')
    op.drop_table('shipments')
    op.execute('DROP SEQUENCE IF EXISTS shipments_id_seq')
    op.drop_index(op.f('ix_shipment_items_uuid'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_updated_by'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_product_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_deleted_at'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_created_by'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.execute('DROP SEQUENCE IF EXISTS shipment_items_id_seq')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_updated_by'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_table('products')
    op.execute('DROP SEQUENCE IF EXISTS products_id_seq')
    op.drop_index(op.f('ix_payments_uuid'), table_name='payments')
    op.drop_index(op.f('ix_payments_updated_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_deleted_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_contract_id'), table_name='payments')
    op.drop_table('payments')
    op.execute('DROP SEQUENCE IF EXISTS payments_id_seq')
    op.drop_index(op.f('ix_payment_allocations_uuid'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_updated_by'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_shipment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_deleted_at'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_created_by'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.execute('DROP SEQUENCE IF EXISTS payment_allocations_id_seq')
    op.drop_index(op.f('ix_exchange_rates_uuid'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_updated_by'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_rate_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_deleted_at'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_created_by'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.execute('DROP SEQUENCE IF EXISTS exchange_rates_id_seq')
    op.drop_index(op.f('ix_contragents_uuid'), table_name='contragents')
    op.drop_index(op.f('ix_contragents_updated_by'), table_name='contragents')
    op.drop_index(op.f('ix_contragents_name'), table_name='contragents')
    op.drop_index(op.f('ix_contragents_deleted_at'), table_name='contragents')
    op.drop_index(op.f('ix_contragents_created_by'), table_name='contragents')
    op.drop_table('contragents')
    op.execute('DROP SEQUENCE IF EXISTS contragents_id_seq')
    op.drop_index(op.f('ix_contracts_uuid'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_updated_by'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_deleted_at'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_created_by'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contragent_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.execute('DROP SEQUENCE IF EXISTS contracts_id_seq')
    op.drop_index(op.f('ix_contract_specifications_uuid'), table_name='contract_specifications')
    op.drop_index(op.f('ix_contract_specifications_updated_by'), table_name='contract_specifications')
    op.drop_index(op.f('ix_contract_specifications_product_id'), table_name='contract_specifications')
    op.drop_index(op.f('ix_contract_specifications_deleted_at'), table_name='contract_specifications')
    op.drop_index(op.f('ix_contract_specifications_created_by'), table_name='contract_specifications')
    op.drop_index(op.f('ix_contract_specifications_contract_id'), table_name='contract_specifications')
    op.drop_table('contract_specifications')
    op.execute('DROP SEQUENCE IF EXISTS contract_specifications_id_seq')
    # ### end Alembic commands ###
